version: '2'
services:
  home:
    image: omelhoro1/homepage
    container_name: home
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    labels:
      - "traefik.frontend.rules=Host:home.igor-fischer.rocks,home.fischerops.com"
    networks:
      - proxy-tier
networks:
  proxy-tier:
    external: true
