version: '2'
services:
  home:
    image: omelhoro1/homepage
    container_name: home-cdn
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    labels:
      - "traefik.frontend.rule=Host:home-cdn.igor-fischer.rocks,home-cdn.fischerops.com"
    networks:
      - proxy-tier
networks:
  proxy-tier:
    external: true
